#!/bin/bash

TEXT="$1"
GRAMMAR="$2"

TT="`which tree-tagger-english`"
VISLCG="`which vislcg3`"

# empty baseform needs to be put into input, otherwise vislcg3 messes up
cat "$TEXT" \
   | "$TT"  \
   | awk '{print("\"<" $1 ">\"") ; print("\t\"\"",$2)}' \
   | "$VISLCG" -g "$GRAMMAR"
